name: Lint

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install uv
      uses: astral-sh/setup-uv@v3
    
    - name: Set up Python
      run: uv python install 3.12
    
    - name: Install dependencies
      run: uv sync --dev
    
    - name: Add ruff
      run: uv add --dev ruff
    
    - name: Lint with ruff
      run: uv run ruff check --output-format=github .
    
    - name: Check formatting with ruff
      run: uv run ruff format --check .
